[project]
name = "icardgenerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sarathrajendran552", email = "sarath.tg@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "cryptography>=50.0.1",
    "glymur>=0.14.8",
    "opencv-python>=5.0.0.93",
    "packaging>=26.3",
    "pillow>=12.3.0",
    "qrcode>=8.2",
]

[project.scripts]
icardgenerator = "icardgenerator:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
